---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: premiers-pas-hello-world
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: premiers-pas-hello-world
      port: 80
