---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv-static
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    type: Directory
    path: /mnt/k8s/pv/hostpath
