---
apiVersion: v1
kind: Pod
metadata:
  name: secret-example
spec:
  containers:
    - name: alpine
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      command:
        - sh
        - -c
        - |
          ls -l /etc/mysecret
          cat /etc/mysecret/*
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/mysecret"
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: mysecret-example
