---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: organisation-selector-front-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      environment: prod
      component: app
      tier: front
  template:
    metadata:
      labels:
        environment: prod
        component: app
        tier: front
    spec:
      containers:
        - name: alpine
          image: tutum/hello-world:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 0
              memory: 0
