---
apiVersion: v1
kind: Service
metadata:
  name: organisation-selector-front-dev
  labels:
    chapter: healthcheck
    section: requests
spec:
  ports:
    - port: 80
  selector:
    environment: dev
    component: app
    tier: front
