---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-basic-helloworld
spec:
  selector:
    matchLabels:
      app: kustomize-basic-helloworld
  template:
    metadata:
      labels:
        app: kustomize-basic-helloworld
    spec:
      containers:
      - name: app
        image: tutum/hello-world:latest
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
