---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# Les attributs à appliquer à l'ensemble des ressources
# Liste exhaustive : https://kubectl.docs.kubernetes.io/references/kustomize/
nameSuffix: -formateur
commonLabels:
  mykey: myvalue
namespace: kustomize-basic-formateur


# Les ressources visées par le templating
resources:
  - service.yaml
  - deployment.yaml
