---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-example
spec:
  selector:
    chapter: service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - 192.168.100.55
