---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: type-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: type-deployment
  template:
    metadata:
      labels:
        app: type-deployment
    spec:
      containers:
        - name: hello-world
          image: tutum/hello-world:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
