---
apiVersion: v1
kind: Service
metadata:
  name: type-statefulset-service
  labels:
    app: type-statefulset-service
spec:
  ports:
    - port: 80
  clusterIP: None
  selector:
    app: type-statefulset
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: type-statefulset
spec:
  replicas: 2
  serviceName: "type-statefulset-service"
  selector:
    matchLabels:
      app: type-statefulset
  template:
    metadata:
      labels:
        app: type-statefulset
        app2: type-statefulset2
    spec:
      containers:
        - name: hello-world
          image: tutum/hello-world:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
