---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


# Les attributs à appliquer à l'ensemble des ressources
# Liste exhaustive : https://kubectl.docs.kubernetes.io/references/kustomize/
commonLabels:
  madewith: kustomize
  environment: prod
namespace: kustomize-advanced-formateur
nameSuffix: '-formateur'

# Les ressources visées par le templating
bases:
  - ../../base
patches:
  - replicas.yaml
