---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomize-advanced-helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kustomize-advanced-helloworld
  template:
    metadata:
      labels:
        app: kustomize-advanced-helloworld
    spec:
      containers:
      - name: app
        image: tutum/hello-world:latest
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
