---
apiVersion: v1
kind: Pod
metadata:
  name: organisation-labels-front-dev
  labels:
    project: formation-kubernetes-labels
    environment: dev
    component: app
    tier: front
spec:
  containers:
    - name: alpine
      image: tutum/hello-world:latest
      imagePullPolicy: IfNotPresent
