---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-webapp
spec:
  ingressClassName: nginx
  rules:
  - host: "ingress.webapp"
    http:
      paths:
      - path: /myname
        pathType: Prefix
        backend:
          service:
            name: ingress-webapp
            port:
              number: 80
