---
apiVersion: v1
kind: Pod
metadata:
  name: persistent-volume-dynamic
spec:
  containers:
    - image: nodevops/nginx-log2fs:1.12-alpine
      name: log2fs
      volumeMounts:
        - name: mypv
          mountPath: /var/log/nginx
  volumes:
    - name: mypv
      persistentVolumeClaim:
        claimName: mypvc-dynamic
