---
apiVersion: v1
kind: Pod
metadata:
  name: init-container-data
spec:
  initContainers:
    - name: prepare
      image: alpine:latest
      command:
        - /bin/sh
        - -c
        - echo "I am an initContainer" > /mnt/shared
      volumeMounts:
        - name: shared-data
          mountPath: /mnt
  containers:
    - name: main
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -c
        - |
          cat /mnt/shared
          sleep infinity
      volumeMounts:
        - name: shared-data
          mountPath: /mnt
  volumes:
    - name: shared-data
      emptyDir: {}
