---
apiVersion: v1
kind: Pod
metadata:
  name: init-container-data
spec:
  initContainers:
    ...
  containers:
    - name: alpine
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
