---
apiVersion: v1
kind: Pod
metadata:
  name: init-container-hello-world
spec:
  initContainers:
    ...
  containers:
    - name: hello-world
      image: tutum/hello-world:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
