---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingresscontroller-webapp
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: ingresscontroller-webapp
      port:
        number: 80
