---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-tcp
spec:
  containers:
    - name: liveness-tcp
      image: registry.k8s.io/liveness
      imagePullPolicy: IfNotPresent
      args:
        - /server
      ports:
        - containerPort: 8080
      livenessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 3
        periodSeconds: 3
