---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec
spec:
  containers:
    - name: liveness-exec
      image: k8s.gcr.io/busybox
      args:
        - /bin/sh
        - -c
        - |
          touch /tmp/healthy; sleep 20; rm -rf /tmp/healthy; sleep infinity
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
