---
apiVersion: v1
kind: Pod
metadata:
  name: liveness-http-headers
spec:
  containers:
    - name: liveness-http-headers
      image: registry.k8s.io/liveness
      # Image: Le endpoint :8080/health
      # - renvoie un code retour 200 les 10 premières secondes
      # - renvoie un code retour 500 ensuite
      # URL: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
      args:
        - /server
      livenessProbe:
        httpGet:
          path: /healthz
          port: 8080
          httpHeaders:
            - name: Custom-Header
              value: Awesome
        initialDelaySeconds: 3
        periodSeconds: 3
