---
apiVersion: v1
kind: Pod
metadata:
  name: discovery
  labels:
    chapter: service
spec:
  containers:
    - name: hello-world
      image: tutum/hello-world:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
