---
apiVersion: v1
kind: Pod
metadata:
  name: envar-echo
spec:
  containers:
    - name: envar-demo-container
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      command:
        - sh
        - -c
        - sleep infinity
      env:
        - name: USERNAME
          value: "myusername"
